// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "brand", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "store_items", Type: field.TypeInt},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "items_stores_items",
				Columns:    []*schema.Column{ItemsColumns[6]},
				RefColumns: []*schema.Column{StoresColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "item_name_brand",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[3], ItemsColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Type: "FULLTEXT",
				},
			},
		},
	}
	// ListsColumns holds the columns for the "lists" table.
	ListsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Default: "my new list"},
		{Name: "user_lists", Type: field.TypeInt},
	}
	// ListsTable holds the schema information for the "lists" table.
	ListsTable = &schema.Table{
		Name:       "lists",
		Columns:    ListsColumns,
		PrimaryKey: []*schema.Column{ListsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lists_users_lists",
				Columns:    []*schema.Column{ListsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "store_id", Type: field.TypeString, Unique: true},
		{Name: "grocer", Type: field.TypeEnum, Enums: []string{"store_a", "store_b", "store_c"}},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// ListItemsColumns holds the columns for the "list_items" table.
	ListItemsColumns = []*schema.Column{
		{Name: "list_id", Type: field.TypeInt},
		{Name: "item_id", Type: field.TypeInt},
	}
	// ListItemsTable holds the schema information for the "list_items" table.
	ListItemsTable = &schema.Table{
		Name:       "list_items",
		Columns:    ListItemsColumns,
		PrimaryKey: []*schema.Column{ListItemsColumns[0], ListItemsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "list_items_list_id",
				Columns:    []*schema.Column{ListItemsColumns[0]},
				RefColumns: []*schema.Column{ListsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "list_items_item_id",
				Columns:    []*schema.Column{ListItemsColumns[1]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemsTable,
		ListsTable,
		StoresTable,
		UsersTable,
		ListItemsTable,
	}
)

func init() {
	ItemsTable.ForeignKeys[0].RefTable = StoresTable
	ListsTable.ForeignKeys[0].RefTable = UsersTable
	ListItemsTable.ForeignKeys[0].RefTable = ListsTable
	ListItemsTable.ForeignKeys[1].RefTable = ItemsTable
}
