// Code generated by ent, DO NOT EDIT.

package ent

import (
	"offgrocery-assessment/internal/ent/item"
	"offgrocery-assessment/internal/ent/list"
	"offgrocery-assessment/internal/ent/schema"
	"offgrocery-assessment/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemMixin := schema.Item{}.Mixin()
	itemMixinFields0 := itemMixin[0].Fields()
	_ = itemMixinFields0
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCreateTime is the schema descriptor for create_time field.
	itemDescCreateTime := itemMixinFields0[0].Descriptor()
	// item.DefaultCreateTime holds the default value on creation for the create_time field.
	item.DefaultCreateTime = itemDescCreateTime.Default.(func() time.Time)
	// itemDescUpdateTime is the schema descriptor for update_time field.
	itemDescUpdateTime := itemMixinFields0[1].Descriptor()
	// item.DefaultUpdateTime holds the default value on creation for the update_time field.
	item.DefaultUpdateTime = itemDescUpdateTime.Default.(func() time.Time)
	// item.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	item.UpdateDefaultUpdateTime = itemDescUpdateTime.UpdateDefault.(func() time.Time)
	// itemDescName is the schema descriptor for name field.
	itemDescName := itemFields[0].Descriptor()
	// item.NameValidator is a validator for the "name" field. It is called by the builders before save.
	item.NameValidator = itemDescName.Validators[0].(func(string) error)
	// itemDescBrand is the schema descriptor for brand field.
	itemDescBrand := itemFields[1].Descriptor()
	// item.BrandValidator is a validator for the "brand" field. It is called by the builders before save.
	item.BrandValidator = itemDescBrand.Validators[0].(func(string) error)
	// itemDescPrice is the schema descriptor for price field.
	itemDescPrice := itemFields[2].Descriptor()
	// item.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	item.PriceValidator = itemDescPrice.Validators[0].(func(float64) error)
	listMixin := schema.List{}.Mixin()
	listMixinFields0 := listMixin[0].Fields()
	_ = listMixinFields0
	listFields := schema.List{}.Fields()
	_ = listFields
	// listDescCreateTime is the schema descriptor for create_time field.
	listDescCreateTime := listMixinFields0[0].Descriptor()
	// list.DefaultCreateTime holds the default value on creation for the create_time field.
	list.DefaultCreateTime = listDescCreateTime.Default.(func() time.Time)
	// listDescUpdateTime is the schema descriptor for update_time field.
	listDescUpdateTime := listMixinFields0[1].Descriptor()
	// list.DefaultUpdateTime holds the default value on creation for the update_time field.
	list.DefaultUpdateTime = listDescUpdateTime.Default.(func() time.Time)
	// list.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	list.UpdateDefaultUpdateTime = listDescUpdateTime.UpdateDefault.(func() time.Time)
	// listDescName is the schema descriptor for name field.
	listDescName := listFields[0].Descriptor()
	// list.DefaultName holds the default value on creation for the name field.
	list.DefaultName = listDescName.Default.(string)
	// list.NameValidator is a validator for the "name" field. It is called by the builders before save.
	list.NameValidator = listDescName.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
}
